version: '3.0'

services:
  account-manager:
    build: ./account-manager
    container_name: account-manager
    command: 9011 "Server 1"
    ports: 
      - "9011:9011"

  reporting-service:
    build: ./reporting-service
    container_name: reporting-service
    command: 9012 "Server 2"
    ports: 
      - "9013:9013"

  user-notification-service:
    build: ./user-notification-service
    container_name: user-notification-service
    command: 9013 "Server 3"
    ports:
      - "9014:9014"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka0:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka0:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_CREATE_TOPICS: "valid-transactions:1:1, suspicious-transactions:1:1"